language: node_js
node_js:
  - "8.1.1"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools @angular/cli

script:
  - cd app/
  - npm run ci
  - cd ../functions/
  - npm install
  - cd ..

deploy:
  skip_cleanup: true
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email:
    on_failure: change
    on_success: change
