language: node_js
node_js:
  - "8.1.1"

branches:
  only:
    - master

install:
  - npm install -g firebase-tools @angular/cli
  - cd app/
  - npm install
  - cd ..

script:
  - cd functions/
  - npm install
  - cd ../app
  - npm run ci

after_success:
    - firebase deploy --token $FIREBASE_TOKEN --non-interactive --only hosting

notifications:
  email:
    on_failure: change
    on_success: change
