language: node_js
node_js:
  - "8.1.1"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools @angular/cli

script:
  - npm run ci
  - cd functions/ && npm install

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --only functions
  - cd .. && firebase deploy --token $FIREBASE_TOKEN


notifications:
  email:
    on_failure: change
    on_success: change
